version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-app
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /apps/jellyfin/media:/media
    restart: "always"
